name: female_metal_voices
description: A new Flutter project.
version: 1.2.1+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher:
    git:
      url: git://github.com/flutter/plugins
      path: packages/url_launcher

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/json/tarja_albums.json
    - assets/card1.jpg
    - assets/card2.jpg
    - assets/card3.jpg
    - assets/_2007_mws.jpg
    - assets/_2010_wlb.jpg
    - assets/_2012_act11.jpg
    - assets/_2013_citd.jpg
    - assets/_2016_tss.jpg

fonts:
     - family: petita
       fonts:
         - asset: assets/PetitaMedium.ttf
         - asset: assets/PetitaBold.ttf
           weight: 700
         - asset: assets/PetitaLight.ttf
           weight: 300
     - family: gidole
       fonts:
         - asset: assets/Gidole-Regular.ttf